"""initial state

Revision ID: 2abfa64f6b33
Revises: 
Create Date: 2026-03-04 18:18:08.091234

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = '2abfa64f6b33'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - ajustado manualmente ###
    
    # Verificar si la tabla ya existe antes de crearla
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()
    
    if 'users' not in tables:
        op.create_table('users',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('username', sa.String(length=100), nullable=False),
            sa.Column('password', sa.String(length=200), nullable=False),
            sa.Column('role', sa.String(length=100), server_default='user', nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('username', name='uq_users_username')
        )
        print("✅ Tabla 'users' creada.")
    else:
        print("ℹ️ La tabla 'users' ya existe, verificando estructura...")
        
        # Verificar columnas existentes
        columns = [col['name'] for col in inspector.get_columns('users')]
        
        # Añadir columnas faltantes si es necesario
        if 'role' not in columns:
            op.add_column('users', sa.Column('role', sa.String(length=100), server_default='user'))
            print("✅ Columna 'role' añadida.")
    
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - ajustado manualmente ###
    
    # Eliminar la tabla (¡CUIDADO! Esto borra todos los datos)
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()
    
    if 'users' in tables:
        op.drop_table('users')
        print("✅ Tabla 'users' eliminada.")
    # ### end Alembic commands ###